---

- name: Installing necessary system packages
  apt:
    name: "{{ hm_griffin_watchee__install_packages[ansible_os_family|lower]['apt'] }}"
    state: latest
    update_cache: "{{ hm_griffin_watchee__apt_force_update }}"

- name: Installing Telegraf from remote URL
  apt:
    deb: "{{ hm_griffin_watchee__deb_url_telegraf }}"
